services:
  # pgAdmin (Compartilhado entre Dev e Prd)
  pgadmin:
    container_name: fantasy_portal_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./database/shared/pgadmin/servers.json:/pgadmin4/servers.json
      - ./database/shared/pgadmin/data:/var/lib/pgadmin
    ports:
      - "25036:80"
    networks:
      - duplecake-net

networks:
  duplecake-net:
    external: true
